name: first action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
      steps:
        - name: printing hello
          run: echo "Hello world welcome to GitHub Actions"
        - name: printing bye
          run: echo "Bye!!!!"
